/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LivescoresRouteRouteImport } from './routes/livescores/route'
import { Route as GlossaryRouteRouteImport } from './routes/glossary/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamsIndexRouteImport } from './routes/streams/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as PrivacyPolicyIndexRouteImport } from './routes/privacy-policy/index'
import { Route as LivescoresIndexRouteImport } from './routes/livescores/index'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as StreamsFixTypeRouteRouteImport } from './routes/streams/$fixType/route'
import { Route as QuizQuizIdIndexRouteImport } from './routes/quiz/$quizId/index'
import { Route as LivescoresFixtureTypeIndexRouteImport } from './routes/livescores/$fixtureType/index'
import { Route as GlossaryFixtypeIndexRouteImport } from './routes/glossary/$fixtype/index'
import { Route as ArticlesArticleSlugIndexRouteImport } from './routes/articles/$articleSlug/index'
import { Route as QuizQuizIdLeaderboardRouteImport } from './routes/quiz/$quizId/leaderboard'
import { Route as ArticlesCategoriesCategorySlugRouteImport } from './routes/articles/categories/$categorySlug'
import { Route as LivescoresLeaguesLeagueIdRouteRouteImport } from './routes/livescores/leagues/$leagueId/route'
import { Route as LivescoresFixtureTypeFixtureIdRouteRouteImport } from './routes/livescores/$fixtureType/$fixtureId/route'
import { Route as StreamsFixTypeFixturesIndexRouteImport } from './routes/streams/$fixType/fixtures/index'
import { Route as LivescoresLeaguesLeagueIdIndexRouteImport } from './routes/livescores/leagues/$leagueId/index'
import { Route as LivescoresFixtureTypeFixtureIdIndexRouteImport } from './routes/livescores/$fixtureType/$fixtureId/index'
import { Route as LivescoresLeaguesLeagueIdStandingsRouteImport } from './routes/livescores/leagues/$leagueId/standings'
import { Route as LivescoresLeaguesLeagueIdScorersRouteImport } from './routes/livescores/leagues/$leagueId/scorers'
import { Route as LivescoresFixtureTypeFixtureIdOverviewRouteImport } from './routes/livescores/$fixtureType/$fixtureId/overview'
import { Route as LivescoresFixtureTypeFixtureIdLineupsRouteImport } from './routes/livescores/$fixtureType/$fixtureId/lineups'
import { Route as StreamsFixTypeFixturesFixIdRouteRouteImport } from './routes/streams/$fixType/fixtures/$fixId/route'
import { Route as StreamsFixTypeFixturesFixIdIndexRouteImport } from './routes/streams/$fixType/fixtures/$fixId/index'
import { Route as StreamsFixTypeFixturesFixIdStatsRouteImport } from './routes/streams/$fixType/fixtures/$fixId/stats'
import { Route as StreamsFixTypeFixturesFixIdLowerThirdRouteImport } from './routes/streams/$fixType/fixtures/$fixId/lower-third'
import { Route as StreamsFixTypeFixturesFixIdLineupsRouteImport } from './routes/streams/$fixType/fixtures/$fixId/lineups'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LivescoresRouteRoute = LivescoresRouteRouteImport.update({
  id: '/livescores',
  path: '/livescores',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRouteRoute = GlossaryRouteRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsIndexRoute = StreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyIndexRoute = PrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivescoresIndexRoute = LivescoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LivescoresRouteRoute,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GlossaryRouteRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const StreamsFixTypeRouteRoute = StreamsFixTypeRouteRouteImport.update({
  id: '/streams/$fixType',
  path: '/streams/$fixType',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdIndexRoute = QuizQuizIdIndexRouteImport.update({
  id: '/quiz/$quizId/',
  path: '/quiz/$quizId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivescoresFixtureTypeIndexRoute =
  LivescoresFixtureTypeIndexRouteImport.update({
    id: '/$fixtureType/',
    path: '/$fixtureType/',
    getParentRoute: () => LivescoresRouteRoute,
  } as any)
const GlossaryFixtypeIndexRoute = GlossaryFixtypeIndexRouteImport.update({
  id: '/$fixtype/',
  path: '/$fixtype/',
  getParentRoute: () => GlossaryRouteRoute,
} as any)
const ArticlesArticleSlugIndexRoute =
  ArticlesArticleSlugIndexRouteImport.update({
    id: '/articles/$articleSlug/',
    path: '/articles/$articleSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuizQuizIdLeaderboardRoute = QuizQuizIdLeaderboardRouteImport.update({
  id: '/quiz/$quizId/leaderboard',
  path: '/quiz/$quizId/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesCategoriesCategorySlugRoute =
  ArticlesCategoriesCategorySlugRouteImport.update({
    id: '/articles/categories/$categorySlug',
    path: '/articles/categories/$categorySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const LivescoresLeaguesLeagueIdRouteRoute =
  LivescoresLeaguesLeagueIdRouteRouteImport.update({
    id: '/leagues/$leagueId',
    path: '/leagues/$leagueId',
    getParentRoute: () => LivescoresRouteRoute,
  } as any)
const LivescoresFixtureTypeFixtureIdRouteRoute =
  LivescoresFixtureTypeFixtureIdRouteRouteImport.update({
    id: '/$fixtureType/$fixtureId',
    path: '/$fixtureType/$fixtureId',
    getParentRoute: () => LivescoresRouteRoute,
  } as any)
const StreamsFixTypeFixturesIndexRoute =
  StreamsFixTypeFixturesIndexRouteImport.update({
    id: '/fixtures/',
    path: '/fixtures/',
    getParentRoute: () => StreamsFixTypeRouteRoute,
  } as any)
const LivescoresLeaguesLeagueIdIndexRoute =
  LivescoresLeaguesLeagueIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LivescoresLeaguesLeagueIdRouteRoute,
  } as any)
const LivescoresFixtureTypeFixtureIdIndexRoute =
  LivescoresFixtureTypeFixtureIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LivescoresFixtureTypeFixtureIdRouteRoute,
  } as any)
const LivescoresLeaguesLeagueIdStandingsRoute =
  LivescoresLeaguesLeagueIdStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => LivescoresLeaguesLeagueIdRouteRoute,
  } as any)
const LivescoresLeaguesLeagueIdScorersRoute =
  LivescoresLeaguesLeagueIdScorersRouteImport.update({
    id: '/scorers',
    path: '/scorers',
    getParentRoute: () => LivescoresLeaguesLeagueIdRouteRoute,
  } as any)
const LivescoresFixtureTypeFixtureIdOverviewRoute =
  LivescoresFixtureTypeFixtureIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LivescoresFixtureTypeFixtureIdRouteRoute,
  } as any)
const LivescoresFixtureTypeFixtureIdLineupsRoute =
  LivescoresFixtureTypeFixtureIdLineupsRouteImport.update({
    id: '/lineups',
    path: '/lineups',
    getParentRoute: () => LivescoresFixtureTypeFixtureIdRouteRoute,
  } as any)
const StreamsFixTypeFixturesFixIdRouteRoute =
  StreamsFixTypeFixturesFixIdRouteRouteImport.update({
    id: '/fixtures/$fixId',
    path: '/fixtures/$fixId',
    getParentRoute: () => StreamsFixTypeRouteRoute,
  } as any)
const StreamsFixTypeFixturesFixIdIndexRoute =
  StreamsFixTypeFixturesFixIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StreamsFixTypeFixturesFixIdRouteRoute,
  } as any)
const StreamsFixTypeFixturesFixIdStatsRoute =
  StreamsFixTypeFixturesFixIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => StreamsFixTypeFixturesFixIdRouteRoute,
  } as any)
const StreamsFixTypeFixturesFixIdLowerThirdRoute =
  StreamsFixTypeFixturesFixIdLowerThirdRouteImport.update({
    id: '/lower-third',
    path: '/lower-third',
    getParentRoute: () => StreamsFixTypeFixturesFixIdRouteRoute,
  } as any)
const StreamsFixTypeFixturesFixIdLineupsRoute =
  StreamsFixTypeFixturesFixIdLineupsRouteImport.update({
    id: '/lineups',
    path: '/lineups',
    getParentRoute: () => StreamsFixTypeFixturesFixIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRouteRouteWithChildren
  '/livescores': typeof LivescoresRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/streams/$fixType': typeof StreamsFixTypeRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/articles/': typeof ArticlesIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/livescores/': typeof LivescoresIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/streams/': typeof StreamsIndexRoute
  '/livescores/$fixtureType/$fixtureId': typeof LivescoresFixtureTypeFixtureIdRouteRouteWithChildren
  '/livescores/leagues/$leagueId': typeof LivescoresLeaguesLeagueIdRouteRouteWithChildren
  '/articles/categories/$categorySlug': typeof ArticlesCategoriesCategorySlugRoute
  '/quiz/$quizId/leaderboard': typeof QuizQuizIdLeaderboardRoute
  '/articles/$articleSlug/': typeof ArticlesArticleSlugIndexRoute
  '/glossary/$fixtype/': typeof GlossaryFixtypeIndexRoute
  '/livescores/$fixtureType/': typeof LivescoresFixtureTypeIndexRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
  '/streams/$fixType/fixtures/$fixId': typeof StreamsFixTypeFixturesFixIdRouteRouteWithChildren
  '/livescores/$fixtureType/$fixtureId/lineups': typeof LivescoresFixtureTypeFixtureIdLineupsRoute
  '/livescores/$fixtureType/$fixtureId/overview': typeof LivescoresFixtureTypeFixtureIdOverviewRoute
  '/livescores/leagues/$leagueId/scorers': typeof LivescoresLeaguesLeagueIdScorersRoute
  '/livescores/leagues/$leagueId/standings': typeof LivescoresLeaguesLeagueIdStandingsRoute
  '/livescores/$fixtureType/$fixtureId/': typeof LivescoresFixtureTypeFixtureIdIndexRoute
  '/livescores/leagues/$leagueId/': typeof LivescoresLeaguesLeagueIdIndexRoute
  '/streams/$fixType/fixtures/': typeof StreamsFixTypeFixturesIndexRoute
  '/streams/$fixType/fixtures/$fixId/lineups': typeof StreamsFixTypeFixturesFixIdLineupsRoute
  '/streams/$fixType/fixtures/$fixId/lower-third': typeof StreamsFixTypeFixturesFixIdLowerThirdRoute
  '/streams/$fixType/fixtures/$fixId/stats': typeof StreamsFixTypeFixturesFixIdStatsRoute
  '/streams/$fixType/fixtures/$fixId/': typeof StreamsFixTypeFixturesFixIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/streams/$fixType': typeof StreamsFixTypeRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/articles': typeof ArticlesIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/livescores': typeof LivescoresIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/streams': typeof StreamsIndexRoute
  '/articles/categories/$categorySlug': typeof ArticlesCategoriesCategorySlugRoute
  '/quiz/$quizId/leaderboard': typeof QuizQuizIdLeaderboardRoute
  '/articles/$articleSlug': typeof ArticlesArticleSlugIndexRoute
  '/glossary/$fixtype': typeof GlossaryFixtypeIndexRoute
  '/livescores/$fixtureType': typeof LivescoresFixtureTypeIndexRoute
  '/quiz/$quizId': typeof QuizQuizIdIndexRoute
  '/livescores/$fixtureType/$fixtureId/lineups': typeof LivescoresFixtureTypeFixtureIdLineupsRoute
  '/livescores/$fixtureType/$fixtureId/overview': typeof LivescoresFixtureTypeFixtureIdOverviewRoute
  '/livescores/leagues/$leagueId/scorers': typeof LivescoresLeaguesLeagueIdScorersRoute
  '/livescores/leagues/$leagueId/standings': typeof LivescoresLeaguesLeagueIdStandingsRoute
  '/livescores/$fixtureType/$fixtureId': typeof LivescoresFixtureTypeFixtureIdIndexRoute
  '/livescores/leagues/$leagueId': typeof LivescoresLeaguesLeagueIdIndexRoute
  '/streams/$fixType/fixtures': typeof StreamsFixTypeFixturesIndexRoute
  '/streams/$fixType/fixtures/$fixId/lineups': typeof StreamsFixTypeFixturesFixIdLineupsRoute
  '/streams/$fixType/fixtures/$fixId/lower-third': typeof StreamsFixTypeFixturesFixIdLowerThirdRoute
  '/streams/$fixType/fixtures/$fixId/stats': typeof StreamsFixTypeFixturesFixIdStatsRoute
  '/streams/$fixType/fixtures/$fixId': typeof StreamsFixTypeFixturesFixIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/glossary': typeof GlossaryRouteRouteWithChildren
  '/livescores': typeof LivescoresRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/streams/$fixType': typeof StreamsFixTypeRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/articles/': typeof ArticlesIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/livescores/': typeof LivescoresIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/streams/': typeof StreamsIndexRoute
  '/livescores/$fixtureType/$fixtureId': typeof LivescoresFixtureTypeFixtureIdRouteRouteWithChildren
  '/livescores/leagues/$leagueId': typeof LivescoresLeaguesLeagueIdRouteRouteWithChildren
  '/articles/categories/$categorySlug': typeof ArticlesCategoriesCategorySlugRoute
  '/quiz/$quizId/leaderboard': typeof QuizQuizIdLeaderboardRoute
  '/articles/$articleSlug/': typeof ArticlesArticleSlugIndexRoute
  '/glossary/$fixtype/': typeof GlossaryFixtypeIndexRoute
  '/livescores/$fixtureType/': typeof LivescoresFixtureTypeIndexRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
  '/streams/$fixType/fixtures/$fixId': typeof StreamsFixTypeFixturesFixIdRouteRouteWithChildren
  '/livescores/$fixtureType/$fixtureId/lineups': typeof LivescoresFixtureTypeFixtureIdLineupsRoute
  '/livescores/$fixtureType/$fixtureId/overview': typeof LivescoresFixtureTypeFixtureIdOverviewRoute
  '/livescores/leagues/$leagueId/scorers': typeof LivescoresLeaguesLeagueIdScorersRoute
  '/livescores/leagues/$leagueId/standings': typeof LivescoresLeaguesLeagueIdStandingsRoute
  '/livescores/$fixtureType/$fixtureId/': typeof LivescoresFixtureTypeFixtureIdIndexRoute
  '/livescores/leagues/$leagueId/': typeof LivescoresLeaguesLeagueIdIndexRoute
  '/streams/$fixType/fixtures/': typeof StreamsFixTypeFixturesIndexRoute
  '/streams/$fixType/fixtures/$fixId/lineups': typeof StreamsFixTypeFixturesFixIdLineupsRoute
  '/streams/$fixType/fixtures/$fixId/lower-third': typeof StreamsFixTypeFixturesFixIdLowerThirdRoute
  '/streams/$fixType/fixtures/$fixId/stats': typeof StreamsFixTypeFixturesFixIdStatsRoute
  '/streams/$fixType/fixtures/$fixId/': typeof StreamsFixTypeFixturesFixIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glossary'
    | '/livescores'
    | '/about'
    | '/streams/$fixType'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/articles/'
    | '/glossary/'
    | '/livescores/'
    | '/privacy-policy/'
    | '/quiz/'
    | '/streams/'
    | '/livescores/$fixtureType/$fixtureId'
    | '/livescores/leagues/$leagueId'
    | '/articles/categories/$categorySlug'
    | '/quiz/$quizId/leaderboard'
    | '/articles/$articleSlug/'
    | '/glossary/$fixtype/'
    | '/livescores/$fixtureType/'
    | '/quiz/$quizId/'
    | '/streams/$fixType/fixtures/$fixId'
    | '/livescores/$fixtureType/$fixtureId/lineups'
    | '/livescores/$fixtureType/$fixtureId/overview'
    | '/livescores/leagues/$leagueId/scorers'
    | '/livescores/leagues/$leagueId/standings'
    | '/livescores/$fixtureType/$fixtureId/'
    | '/livescores/leagues/$leagueId/'
    | '/streams/$fixType/fixtures/'
    | '/streams/$fixType/fixtures/$fixId/lineups'
    | '/streams/$fixType/fixtures/$fixId/lower-third'
    | '/streams/$fixType/fixtures/$fixId/stats'
    | '/streams/$fixType/fixtures/$fixId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/streams/$fixType'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/articles'
    | '/glossary'
    | '/livescores'
    | '/privacy-policy'
    | '/quiz'
    | '/streams'
    | '/articles/categories/$categorySlug'
    | '/quiz/$quizId/leaderboard'
    | '/articles/$articleSlug'
    | '/glossary/$fixtype'
    | '/livescores/$fixtureType'
    | '/quiz/$quizId'
    | '/livescores/$fixtureType/$fixtureId/lineups'
    | '/livescores/$fixtureType/$fixtureId/overview'
    | '/livescores/leagues/$leagueId/scorers'
    | '/livescores/leagues/$leagueId/standings'
    | '/livescores/$fixtureType/$fixtureId'
    | '/livescores/leagues/$leagueId'
    | '/streams/$fixType/fixtures'
    | '/streams/$fixType/fixtures/$fixId/lineups'
    | '/streams/$fixType/fixtures/$fixId/lower-third'
    | '/streams/$fixType/fixtures/$fixId/stats'
    | '/streams/$fixType/fixtures/$fixId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/glossary'
    | '/livescores'
    | '/about'
    | '/streams/$fixType'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify'
    | '/articles/'
    | '/glossary/'
    | '/livescores/'
    | '/privacy-policy/'
    | '/quiz/'
    | '/streams/'
    | '/livescores/$fixtureType/$fixtureId'
    | '/livescores/leagues/$leagueId'
    | '/articles/categories/$categorySlug'
    | '/quiz/$quizId/leaderboard'
    | '/articles/$articleSlug/'
    | '/glossary/$fixtype/'
    | '/livescores/$fixtureType/'
    | '/quiz/$quizId/'
    | '/streams/$fixType/fixtures/$fixId'
    | '/livescores/$fixtureType/$fixtureId/lineups'
    | '/livescores/$fixtureType/$fixtureId/overview'
    | '/livescores/leagues/$leagueId/scorers'
    | '/livescores/leagues/$leagueId/standings'
    | '/livescores/$fixtureType/$fixtureId/'
    | '/livescores/leagues/$leagueId/'
    | '/streams/$fixType/fixtures/'
    | '/streams/$fixType/fixtures/$fixId/lineups'
    | '/streams/$fixType/fixtures/$fixId/lower-third'
    | '/streams/$fixType/fixtures/$fixId/stats'
    | '/streams/$fixType/fixtures/$fixId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GlossaryRouteRoute: typeof GlossaryRouteRouteWithChildren
  LivescoresRouteRoute: typeof LivescoresRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  StreamsFixTypeRouteRoute: typeof StreamsFixTypeRouteRouteWithChildren
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  StreamsIndexRoute: typeof StreamsIndexRoute
  ArticlesCategoriesCategorySlugRoute: typeof ArticlesCategoriesCategorySlugRoute
  QuizQuizIdLeaderboardRoute: typeof QuizQuizIdLeaderboardRoute
  ArticlesArticleSlugIndexRoute: typeof ArticlesArticleSlugIndexRoute
  QuizQuizIdIndexRoute: typeof QuizQuizIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livescores': {
      id: '/livescores'
      path: '/livescores'
      fullPath: '/livescores'
      preLoaderRoute: typeof LivescoresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/': {
      id: '/streams/'
      path: '/streams'
      fullPath: '/streams/'
      preLoaderRoute: typeof StreamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy/': {
      id: '/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof PrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livescores/': {
      id: '/livescores/'
      path: '/'
      fullPath: '/livescores/'
      preLoaderRoute: typeof LivescoresIndexRouteImport
      parentRoute: typeof LivescoresRouteRoute
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof GlossaryRouteRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/streams/$fixType': {
      id: '/streams/$fixType'
      path: '/streams/$fixType'
      fullPath: '/streams/$fixType'
      preLoaderRoute: typeof StreamsFixTypeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/': {
      id: '/quiz/$quizId/'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof QuizQuizIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livescores/$fixtureType/': {
      id: '/livescores/$fixtureType/'
      path: '/$fixtureType'
      fullPath: '/livescores/$fixtureType/'
      preLoaderRoute: typeof LivescoresFixtureTypeIndexRouteImport
      parentRoute: typeof LivescoresRouteRoute
    }
    '/glossary/$fixtype/': {
      id: '/glossary/$fixtype/'
      path: '/$fixtype'
      fullPath: '/glossary/$fixtype/'
      preLoaderRoute: typeof GlossaryFixtypeIndexRouteImport
      parentRoute: typeof GlossaryRouteRoute
    }
    '/articles/$articleSlug/': {
      id: '/articles/$articleSlug/'
      path: '/articles/$articleSlug'
      fullPath: '/articles/$articleSlug/'
      preLoaderRoute: typeof ArticlesArticleSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/leaderboard': {
      id: '/quiz/$quizId/leaderboard'
      path: '/quiz/$quizId/leaderboard'
      fullPath: '/quiz/$quizId/leaderboard'
      preLoaderRoute: typeof QuizQuizIdLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/categories/$categorySlug': {
      id: '/articles/categories/$categorySlug'
      path: '/articles/categories/$categorySlug'
      fullPath: '/articles/categories/$categorySlug'
      preLoaderRoute: typeof ArticlesCategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livescores/leagues/$leagueId': {
      id: '/livescores/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/livescores/leagues/$leagueId'
      preLoaderRoute: typeof LivescoresLeaguesLeagueIdRouteRouteImport
      parentRoute: typeof LivescoresRouteRoute
    }
    '/livescores/$fixtureType/$fixtureId': {
      id: '/livescores/$fixtureType/$fixtureId'
      path: '/$fixtureType/$fixtureId'
      fullPath: '/livescores/$fixtureType/$fixtureId'
      preLoaderRoute: typeof LivescoresFixtureTypeFixtureIdRouteRouteImport
      parentRoute: typeof LivescoresRouteRoute
    }
    '/streams/$fixType/fixtures/': {
      id: '/streams/$fixType/fixtures/'
      path: '/fixtures'
      fullPath: '/streams/$fixType/fixtures/'
      preLoaderRoute: typeof StreamsFixTypeFixturesIndexRouteImport
      parentRoute: typeof StreamsFixTypeRouteRoute
    }
    '/livescores/leagues/$leagueId/': {
      id: '/livescores/leagues/$leagueId/'
      path: '/'
      fullPath: '/livescores/leagues/$leagueId/'
      preLoaderRoute: typeof LivescoresLeaguesLeagueIdIndexRouteImport
      parentRoute: typeof LivescoresLeaguesLeagueIdRouteRoute
    }
    '/livescores/$fixtureType/$fixtureId/': {
      id: '/livescores/$fixtureType/$fixtureId/'
      path: '/'
      fullPath: '/livescores/$fixtureType/$fixtureId/'
      preLoaderRoute: typeof LivescoresFixtureTypeFixtureIdIndexRouteImport
      parentRoute: typeof LivescoresFixtureTypeFixtureIdRouteRoute
    }
    '/livescores/leagues/$leagueId/standings': {
      id: '/livescores/leagues/$leagueId/standings'
      path: '/standings'
      fullPath: '/livescores/leagues/$leagueId/standings'
      preLoaderRoute: typeof LivescoresLeaguesLeagueIdStandingsRouteImport
      parentRoute: typeof LivescoresLeaguesLeagueIdRouteRoute
    }
    '/livescores/leagues/$leagueId/scorers': {
      id: '/livescores/leagues/$leagueId/scorers'
      path: '/scorers'
      fullPath: '/livescores/leagues/$leagueId/scorers'
      preLoaderRoute: typeof LivescoresLeaguesLeagueIdScorersRouteImport
      parentRoute: typeof LivescoresLeaguesLeagueIdRouteRoute
    }
    '/livescores/$fixtureType/$fixtureId/overview': {
      id: '/livescores/$fixtureType/$fixtureId/overview'
      path: '/overview'
      fullPath: '/livescores/$fixtureType/$fixtureId/overview'
      preLoaderRoute: typeof LivescoresFixtureTypeFixtureIdOverviewRouteImport
      parentRoute: typeof LivescoresFixtureTypeFixtureIdRouteRoute
    }
    '/livescores/$fixtureType/$fixtureId/lineups': {
      id: '/livescores/$fixtureType/$fixtureId/lineups'
      path: '/lineups'
      fullPath: '/livescores/$fixtureType/$fixtureId/lineups'
      preLoaderRoute: typeof LivescoresFixtureTypeFixtureIdLineupsRouteImport
      parentRoute: typeof LivescoresFixtureTypeFixtureIdRouteRoute
    }
    '/streams/$fixType/fixtures/$fixId': {
      id: '/streams/$fixType/fixtures/$fixId'
      path: '/fixtures/$fixId'
      fullPath: '/streams/$fixType/fixtures/$fixId'
      preLoaderRoute: typeof StreamsFixTypeFixturesFixIdRouteRouteImport
      parentRoute: typeof StreamsFixTypeRouteRoute
    }
    '/streams/$fixType/fixtures/$fixId/': {
      id: '/streams/$fixType/fixtures/$fixId/'
      path: '/'
      fullPath: '/streams/$fixType/fixtures/$fixId/'
      preLoaderRoute: typeof StreamsFixTypeFixturesFixIdIndexRouteImport
      parentRoute: typeof StreamsFixTypeFixturesFixIdRouteRoute
    }
    '/streams/$fixType/fixtures/$fixId/stats': {
      id: '/streams/$fixType/fixtures/$fixId/stats'
      path: '/stats'
      fullPath: '/streams/$fixType/fixtures/$fixId/stats'
      preLoaderRoute: typeof StreamsFixTypeFixturesFixIdStatsRouteImport
      parentRoute: typeof StreamsFixTypeFixturesFixIdRouteRoute
    }
    '/streams/$fixType/fixtures/$fixId/lower-third': {
      id: '/streams/$fixType/fixtures/$fixId/lower-third'
      path: '/lower-third'
      fullPath: '/streams/$fixType/fixtures/$fixId/lower-third'
      preLoaderRoute: typeof StreamsFixTypeFixturesFixIdLowerThirdRouteImport
      parentRoute: typeof StreamsFixTypeFixturesFixIdRouteRoute
    }
    '/streams/$fixType/fixtures/$fixId/lineups': {
      id: '/streams/$fixType/fixtures/$fixId/lineups'
      path: '/lineups'
      fullPath: '/streams/$fixType/fixtures/$fixId/lineups'
      preLoaderRoute: typeof StreamsFixTypeFixturesFixIdLineupsRouteImport
      parentRoute: typeof StreamsFixTypeFixturesFixIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GlossaryRouteRouteChildren {
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  GlossaryFixtypeIndexRoute: typeof GlossaryFixtypeIndexRoute
}

const GlossaryRouteRouteChildren: GlossaryRouteRouteChildren = {
  GlossaryIndexRoute: GlossaryIndexRoute,
  GlossaryFixtypeIndexRoute: GlossaryFixtypeIndexRoute,
}

const GlossaryRouteRouteWithChildren = GlossaryRouteRoute._addFileChildren(
  GlossaryRouteRouteChildren,
)

interface LivescoresFixtureTypeFixtureIdRouteRouteChildren {
  LivescoresFixtureTypeFixtureIdLineupsRoute: typeof LivescoresFixtureTypeFixtureIdLineupsRoute
  LivescoresFixtureTypeFixtureIdOverviewRoute: typeof LivescoresFixtureTypeFixtureIdOverviewRoute
  LivescoresFixtureTypeFixtureIdIndexRoute: typeof LivescoresFixtureTypeFixtureIdIndexRoute
}

const LivescoresFixtureTypeFixtureIdRouteRouteChildren: LivescoresFixtureTypeFixtureIdRouteRouteChildren =
  {
    LivescoresFixtureTypeFixtureIdLineupsRoute:
      LivescoresFixtureTypeFixtureIdLineupsRoute,
    LivescoresFixtureTypeFixtureIdOverviewRoute:
      LivescoresFixtureTypeFixtureIdOverviewRoute,
    LivescoresFixtureTypeFixtureIdIndexRoute:
      LivescoresFixtureTypeFixtureIdIndexRoute,
  }

const LivescoresFixtureTypeFixtureIdRouteRouteWithChildren =
  LivescoresFixtureTypeFixtureIdRouteRoute._addFileChildren(
    LivescoresFixtureTypeFixtureIdRouteRouteChildren,
  )

interface LivescoresLeaguesLeagueIdRouteRouteChildren {
  LivescoresLeaguesLeagueIdScorersRoute: typeof LivescoresLeaguesLeagueIdScorersRoute
  LivescoresLeaguesLeagueIdStandingsRoute: typeof LivescoresLeaguesLeagueIdStandingsRoute
  LivescoresLeaguesLeagueIdIndexRoute: typeof LivescoresLeaguesLeagueIdIndexRoute
}

const LivescoresLeaguesLeagueIdRouteRouteChildren: LivescoresLeaguesLeagueIdRouteRouteChildren =
  {
    LivescoresLeaguesLeagueIdScorersRoute:
      LivescoresLeaguesLeagueIdScorersRoute,
    LivescoresLeaguesLeagueIdStandingsRoute:
      LivescoresLeaguesLeagueIdStandingsRoute,
    LivescoresLeaguesLeagueIdIndexRoute: LivescoresLeaguesLeagueIdIndexRoute,
  }

const LivescoresLeaguesLeagueIdRouteRouteWithChildren =
  LivescoresLeaguesLeagueIdRouteRoute._addFileChildren(
    LivescoresLeaguesLeagueIdRouteRouteChildren,
  )

interface LivescoresRouteRouteChildren {
  LivescoresIndexRoute: typeof LivescoresIndexRoute
  LivescoresFixtureTypeFixtureIdRouteRoute: typeof LivescoresFixtureTypeFixtureIdRouteRouteWithChildren
  LivescoresLeaguesLeagueIdRouteRoute: typeof LivescoresLeaguesLeagueIdRouteRouteWithChildren
  LivescoresFixtureTypeIndexRoute: typeof LivescoresFixtureTypeIndexRoute
}

const LivescoresRouteRouteChildren: LivescoresRouteRouteChildren = {
  LivescoresIndexRoute: LivescoresIndexRoute,
  LivescoresFixtureTypeFixtureIdRouteRoute:
    LivescoresFixtureTypeFixtureIdRouteRouteWithChildren,
  LivescoresLeaguesLeagueIdRouteRoute:
    LivescoresLeaguesLeagueIdRouteRouteWithChildren,
  LivescoresFixtureTypeIndexRoute: LivescoresFixtureTypeIndexRoute,
}

const LivescoresRouteRouteWithChildren = LivescoresRouteRoute._addFileChildren(
  LivescoresRouteRouteChildren,
)

interface StreamsFixTypeFixturesFixIdRouteRouteChildren {
  StreamsFixTypeFixturesFixIdLineupsRoute: typeof StreamsFixTypeFixturesFixIdLineupsRoute
  StreamsFixTypeFixturesFixIdLowerThirdRoute: typeof StreamsFixTypeFixturesFixIdLowerThirdRoute
  StreamsFixTypeFixturesFixIdStatsRoute: typeof StreamsFixTypeFixturesFixIdStatsRoute
  StreamsFixTypeFixturesFixIdIndexRoute: typeof StreamsFixTypeFixturesFixIdIndexRoute
}

const StreamsFixTypeFixturesFixIdRouteRouteChildren: StreamsFixTypeFixturesFixIdRouteRouteChildren =
  {
    StreamsFixTypeFixturesFixIdLineupsRoute:
      StreamsFixTypeFixturesFixIdLineupsRoute,
    StreamsFixTypeFixturesFixIdLowerThirdRoute:
      StreamsFixTypeFixturesFixIdLowerThirdRoute,
    StreamsFixTypeFixturesFixIdStatsRoute:
      StreamsFixTypeFixturesFixIdStatsRoute,
    StreamsFixTypeFixturesFixIdIndexRoute:
      StreamsFixTypeFixturesFixIdIndexRoute,
  }

const StreamsFixTypeFixturesFixIdRouteRouteWithChildren =
  StreamsFixTypeFixturesFixIdRouteRoute._addFileChildren(
    StreamsFixTypeFixturesFixIdRouteRouteChildren,
  )

interface StreamsFixTypeRouteRouteChildren {
  StreamsFixTypeFixturesFixIdRouteRoute: typeof StreamsFixTypeFixturesFixIdRouteRouteWithChildren
  StreamsFixTypeFixturesIndexRoute: typeof StreamsFixTypeFixturesIndexRoute
}

const StreamsFixTypeRouteRouteChildren: StreamsFixTypeRouteRouteChildren = {
  StreamsFixTypeFixturesFixIdRouteRoute:
    StreamsFixTypeFixturesFixIdRouteRouteWithChildren,
  StreamsFixTypeFixturesIndexRoute: StreamsFixTypeFixturesIndexRoute,
}

const StreamsFixTypeRouteRouteWithChildren =
  StreamsFixTypeRouteRoute._addFileChildren(StreamsFixTypeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GlossaryRouteRoute: GlossaryRouteRouteWithChildren,
  LivescoresRouteRoute: LivescoresRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  StreamsFixTypeRouteRoute: StreamsFixTypeRouteRouteWithChildren,
  ArticlesIndexRoute: ArticlesIndexRoute,
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  StreamsIndexRoute: StreamsIndexRoute,
  ArticlesCategoriesCategorySlugRoute: ArticlesCategoriesCategorySlugRoute,
  QuizQuizIdLeaderboardRoute: QuizQuizIdLeaderboardRoute,
  ArticlesArticleSlugIndexRoute: ArticlesArticleSlugIndexRoute,
  QuizQuizIdIndexRoute: QuizQuizIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
